# Generated by Django 3.2.20 on 2023-08-01 05:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tldetection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profileImage',
            field=models.FileField(blank=True, default='profileImages/profile_default.png', null=True, upload_to='profileImages/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'mp4'])]),
        ),
    ]
