# Generated by Django 3.2.20 on 2023-08-04 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tldetection', '0004_leadmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profileImage',
        ),
    ]
